### ISSUE TITLE
[PROGRAM PLAN]: The high level development plan for GEOS

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/GEOS#2359]
## Description
This "issue" will track an evolving program plan for the development goals of GEOS from a high level perspective. Major projects will be listed with high level summaries, and their associated `EPIC` will be linked. Detailed discussions about projects should not be present on this `issue`, but rather confined to the associated project `EPIC` .

## Development thrusts
- [ ] Compositional flow / Poromechanics
- [ ] Thermal (Coupling thermal into flow and mechanics)
- [ ] Geochemistry (reactive transport)
- [ ] Faults and Fracturing ( Fractures/Faults, Contact Mechanics,  Hydraulic Fracturing )
- [ ] Geophysics - high order spectral finite element
- [ ] Constitutive Modeling
- [ ] Linear/Nonlinear solver strategies
- [ ] Matrix-Free 
- [ ] Workflow (pygeos, preprocessing, mesh reading, plotting, time histories )
- [ ] Target platforms, testing, benchmarks, deployment
- [ ] Documentation - user manual, tutorials, developer guide, doxygen.

**Comment by joshua-white** [comment]
Looks good.  My only comments:
- Geophysics might grow to include other things, so perhaps just delete the "high order SEM" tag?
- Do you want to merge Matrix-Free under Linear / Nonlinear Solver Strategies, or keep on its own?

**Comment by rrsettgast** [comment]
> Looks good. My only comments:
> 
> * Geophysics might grow to include other things, so perhaps just delete the "high order SEM" tag?
I think "high order SEM" is the first thing on this. 

> * Do you want to merge Matrix-Free under Linear / Nonlinear Solver Strategies, or keep on its own?
I want to keep them separate since they are completely separate paths in the code.

**Comment by herve-gross** [comment]
I have aligned the Slack channels against this plan.
