### ISSUE TITLE
[EPIC] Faults & Fractures 

### ISSUE THREAD

**Issue by CusiniM** [GEOSX/GEOS#2361]
## Description
The goal of this issue is to keep track of all developments related to modeling faults & faults.

## Work Scope
- Couple current fracture modeling capabilities with wells
- Import of external embedded fracture networks
- 

## Issues in this EPIC
- [ ] https://github.com/GEOSX/GEOS/issues/2360
- [ ] Placeholder for issue/PR to couple conforming fractures with wells 
- [ ] Placeholder for issue/PR to couple embedded fractures with wells 
- [ ] Placeholder for issue/PR to implement `MultiphasePoromechanicsConformingFractures`
